# Generated by Django 2.1.5 on 2019-01-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('text', models.TextField(blank=True, db_index=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
